pipeline { 
    agent { label 'co-sf-pe-171' }
    options {
        skipStagesAfterUnstable()
    }
    parameters {
        string(name: 'CODEREPOURL', defaultValue: 'https://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@github.com/sackhade/jenkinsgitrepo.git', description: 'From where to checkout code'),
        string(name: 'EMAILTO', defaultValue: 'skhade@ddn.com', description: 'email addresses or DL separated by comma')
    }
    stages {
        stage('checkout code repo'){
            steps { 
	        echo 'Sending email to: ${EMAILTO}'
                sh 'echo checkout code repo'
		dir('jenkinsgitrepo') {
		    git branch: 'main', 
		    url: '${CODEREPOURL}'

		}
            }
        }
        stage('execute some commands on checked out repo'){
            steps {
                sh 'echo execute some commands on checked out repo'
		dir('jenkinsgitrepo') {
		    sh 'chmod +rx somesampleshellscript.sh'
		    sh 'ls -ltr'
		    sh './somesampleshellscript.sh'
		}
            }
        }
        stage('bye') {
            steps {
                sh 'echo bye'
   	    }
        }
    }
    post {
        always {
            echo 'One way or another, I have finished'
        }
        success {
            echo 'I succeeded!'
	    echo 'Sending email to: ${EMAILTO}'
            mail to: '${EMAILTO}',
	    from: 'pipelinedemo@ddn.com',
            subject: "Succeeded Pipeline: ${currentBuild.fullDisplayName}",
            body: "Build URL here ${env.BUILD_URL}"	    
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
	    mail to: '${EMAILTO}',
            from: 'pipelinedemo@ddn.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
        changed {
            echo 'Things were different before...'
        }
    }
}
