pipeline { 
    agent { label 'co-sf-pe-171' }
    parameters {
        string(name: 'CODEREPOURL', defaultValue: 'https://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@github.com/sackhade/jenkinsgitrepo1.git', description: 'From where to checkout code')
    }
    stages {
        stage('checkout code repo'){
            steps { 
                 sh 'echo checkout code repo jenkinsgitrepo1'
		             dir('jenkinsgitrepo1') {
		                git branch: 'main', 
		                url: "${params.CODEREPOURL}"
                 }
            }
        }
        stage('execute some commands on checked out repo'){
            steps {
                sh 'echo execute some commands on checked out repo'
		            dir('jenkinsgitrepo1') {
		                sh 'chmod +rx somesampleshellscript.sh'
		                sh 'ls -ltr'
		                sh './somesampleshellscript.sh'
		            }
            }
        }
        stage('bye') {
            steps {
                sh 'echo bye for jenkinsgitrepo1'
   	        }
        }
    }
}
